// *** VERSIONS RESTORATION ***

#if (defined GAMEVER_EXEDEF_DCAT100) || (defined GAMEVER_EXEDEF_4HCAT101) || (defined GAMEVER_EXEDEF_5HCAT112) || (defined GAMEVER_EXEDEF_6HCAT113)
#define GAMEVER_SLIDECAT
#endif

#if (defined GAMEVER_EXEDEF_LSCN110S)
#define GAMEVER_LOADSCN
#endif

#if (defined GAMEVER_EXEDEF_4INTR101) || (defined GAMEVER_EXEDEF_4INTR106) || (defined GAMEVER_EXEDEF_5INTR104) || (defined GAMEVER_EXEDEF_6INTR105)
#define GAMEVER_INTRO
#endif

#if (defined GAMEVER_EXEDEF_DCAT100) || (defined GAMEVER_EXEDEF_4INTR101)
#define GAMEVER_SHAREWARE
#endif

#if (defined GAMEVER_SHAREWARE) || (defined GAMEVER_EXEDEF_4HCAT101) || (defined GAMEVER_EXEDEF_4INTR106)
#define GAMEVER_CATABYSS
#endif

#if (defined GAMEVER_EXEDEF_5HCAT112) || (defined GAMEVER_EXEDEF_5INTR104)
#define GAMEVER_CATARM
#endif

#if (defined GAMEVER_EXEDEF_6HCAT113) || (defined GAMEVER_EXEDEF_6INTR105)
#define GAMEVER_CATAPOC
#endif

// Misc. SLIDECAT string

#ifdef GAMEVER_SLIDECAT
#ifdef GAMEVER_CATABYSS
#define GAMEVER_SLIDECAT_ERR_STR "CATALOG ERROR"
#else
#define GAMEVER_SLIDECAT_ERR_STR "ERROR"
#endif
#endif
